-- MySQL Script generated by MySQL Workbench
-- Tue Jun 20 22:29:08 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema aps2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aps2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aps2` DEFAULT CHARACTER SET utf8 ;
USE `aps2` ;

-- -----------------------------------------------------
-- Table `aps2`.`Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aps2`.`Medico` (
  `CRM` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Especialidade` VARCHAR(45) NULL,
  `CPF` VARCHAR(45) NULL,
  `CNPJ` VARCHAR(45) NULL,
  `DataNascimento` VARCHAR(45) NULL,
  `Endereco` VARCHAR(45) NULL,
  `Telefone` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Senha` VARCHAR(45) NULL,
  PRIMARY KEY (`CRM`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aps2`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aps2`.`Paciente` (
  `CPF` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `DataNascimento` VARCHAR(45) NULL,
  `TipoPlano` VARCHAR(45) NULL,
  `Telefone` VARCHAR(45) NULL,
  `Endereco` VARCHAR(45) NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aps2`.`Atendente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aps2`.`Atendente` (
  `idAtendente` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Senha` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`idAtendente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aps2`.`Atendimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aps2`.`Atendimento` (
  `Medico_CRM` INT NOT NULL,
  `Paciente_CPF` INT NOT NULL,
  `idAtendimento` INT NOT NULL,
  PRIMARY KEY (`Medico_CRM`, `Paciente_CPF`, `idAtendimento`),
  INDEX `fk_Medico_has_Paciente_Paciente1_idx` (`Paciente_CPF` ASC) VISIBLE,
  INDEX `fk_Medico_has_Paciente_Medico_idx` (`Medico_CRM` ASC) VISIBLE,
  CONSTRAINT `fk_Medico_has_Paciente_Medico`
    FOREIGN KEY (`Medico_CRM`)
    REFERENCES `aps2`.`Medico` (`CRM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medico_has_Paciente_Paciente1`
    FOREIGN KEY (`Paciente_CPF`)
    REFERENCES `aps2`.`Paciente` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aps2`.`Confirma_Consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aps2`.`Confirma_Consulta` (
  `Atendente_idAtendente` INT NOT NULL,
  `Paciente_CPF` INT NOT NULL,
  `StatusConsulta` VARCHAR(45) NULL,
  `DataConfirmacao` VARCHAR(45) NULL,
  `HoraConfirmacao` VARCHAR(45) NULL,
  PRIMARY KEY (`Atendente_idAtendente`, `Paciente_CPF`),
  INDEX `fk_Atendente_has_Paciente_Paciente1_idx` (`Paciente_CPF` ASC) VISIBLE,
  INDEX `fk_Atendente_has_Paciente_Atendente1_idx` (`Atendente_idAtendente` ASC) VISIBLE,
  CONSTRAINT `fk_Atendente_has_Paciente_Atendente1`
    FOREIGN KEY (`Atendente_idAtendente`)
    REFERENCES `aps2`.`Atendente` (`idAtendente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Atendente_has_Paciente_Paciente1`
    FOREIGN KEY (`Paciente_CPF`)
    REFERENCES `aps2`.`Paciente` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aps2`.`Consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aps2`.`Consulta` (
  `idConsulta` INT NOT NULL,
  `DataConsulta` VARCHAR(45) NULL,
  `HoraConsulta` VARCHAR(45) NULL,
  `TipoConsulta` VARCHAR(45) NULL,
  `Receita` VARCHAR(45) NULL,
  `SolicitacaoRetorno` VARCHAR(45) NULL,
  PRIMARY KEY (`idConsulta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aps2`.`Ficha_Atendimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aps2`.`Ficha_Atendimento` (
  `Consulta_idConsulta` INT NOT NULL,
  `Paciente_CPF` INT NOT NULL,
  `MotivoConsulta` VARCHAR(45) NULL,
  PRIMARY KEY (`Consulta_idConsulta`, `Paciente_CPF`),
  INDEX `fk_Consulta_has_Paciente_Paciente1_idx` (`Paciente_CPF` ASC) VISIBLE,
  INDEX `fk_Consulta_has_Paciente_Consulta1_idx` (`Consulta_idConsulta` ASC) VISIBLE,
  CONSTRAINT `fk_Consulta_has_Paciente_Consulta1`
    FOREIGN KEY (`Consulta_idConsulta`)
    REFERENCES `aps2`.`Consulta` (`idConsulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consulta_has_Paciente_Paciente1`
    FOREIGN KEY (`Paciente_CPF`)
    REFERENCES `aps2`.`Paciente` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aps2`.`Consulta_Marcada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aps2`.`Consulta_Marcada` (
  `Consulta_idConsulta` INT NOT NULL,
  `Paciente_CPF` INT NOT NULL,
  PRIMARY KEY (`Consulta_idConsulta`, `Paciente_CPF`),
  INDEX `fk_Consulta_has_Paciente_Paciente2_idx` (`Paciente_CPF` ASC) VISIBLE,
  INDEX `fk_Consulta_has_Paciente_Consulta2_idx` (`Consulta_idConsulta` ASC) VISIBLE,
  CONSTRAINT `fk_Consulta_has_Paciente_Consulta2`
    FOREIGN KEY (`Consulta_idConsulta`)
    REFERENCES `aps2`.`Consulta` (`idConsulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consulta_has_Paciente_Paciente2`
    FOREIGN KEY (`Paciente_CPF`)
    REFERENCES `aps2`.`Paciente` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
